# -*- coding: utf-8 -*-
"""Pre_entrega_DianaValencia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BpphJSCSZPcqLCjUuz6VOFPKDH-Jq01Y

#**Pre- Entrega**

Diana Carolina Valencia Valencia

c25262 Análisis de datos con python

_________________________________________

Librerias
"""

import pandas as pd
import numpy as np

"""Carga de datos"""

from google.colab import drive
drive.mount('/content/drive')

#Ruta al archivo de texto en tu Google Drive
df_clientes= '/content/drive/MyDrive/TalentoTech_ar/pre_entrega/datasets/clientes.csv'
df_marketing= '/content/drive/MyDrive/TalentoTech_ar/pre_entrega/datasets/marketing.csv'
df_ventas= '/content/drive/MyDrive/TalentoTech_ar/pre_entrega/datasets/ventas.csv'

#Leer archivo
clientes = pd.read_csv(df_clientes)
marketing = pd.read_csv(df_marketing)
ventas = pd.read_csv(df_ventas)

"""Análisis exploratorio de datos"""

print("="*20, "Análisis Exploratorio de los clientes", "="*20)
print("\nInformación de los clientes\n", clientes.info())
print("\nPrimeras 5 filas\n", clientes.head(5), "\nUltimas filas\n", clientes.tail(2))
print("\nDimensiones dataframe clientes\n", clientes.shape)
print("\nTipo de datos del df clientes\n", clientes.dtypes)
print("\nEstadistica descriptiva de los clientes\n", clientes.describe())

print("="*20, "Análisis Exploratorio de Marketing", "="*20)
print("\n Información de marketing\n", marketing.info())
print("\n Primeras 5 filas\n", marketing.head(5), "\nUltimas filas\n", marketing.tail(2))
print("\n Dimensiones dataframe marketing\n", marketing.shape)
print("\n Tipo de datos del df marketing\n", marketing.dtypes)
print("\n Estadistica descriptiva de los marketing\n", marketing.describe())

print("="*20, "Análisis Exploratorio de las ventas", "="*20)
print("\nInformación de las ventas\n", ventas.info())
print("\nPrimeras 5 filas\n", ventas.head(5), "\nUltimas filas\n", ventas.tail(2))
print("\nDimensiones dataframe ventas\n", ventas.shape)
print("\nTipo de datos del df ventas\n", ventas.dtypes)
print("\nEstadistica descriptiva de las ventas\n", ventas.describe())

"""Revisión: Calidad de los conjuntos de datos"""

#Nulos
print("\nNulos del df clientes\n", clientes.isna().sum())
print("\nNulos del df marketing\n", marketing.isna().sum())
print("\nNulos del df ventas\n", ventas.isna().sum())

#Revisar duplicados
print("Dulicados del df clientes:", clientes.duplicated(keep=False).sum())
print("Dulicados del df marketing:",marketing.duplicated(keep=False).sum())
print("Duplicados del df ventas:",ventas.duplicated(keep=False).sum())

#Identificar filas con duplicados del df ventas
duplicados_ventas = ventas[ventas.duplicated(keep=False)]
display(duplicados_ventas)

#Identificar valores repetidos por columna del ventas
ventas.duplicated(subset=ventas.columns, keep='first').sum()

"""Limpieza, normalización y transformación de datos"""

#Crear copias de los df
clientes_2 = clientes.copy()
marketing_2 = marketing.copy()
ventas_2 = ventas.copy()

#Eliminar duplicados de ventas_2
ventas_2 = ventas_2.drop_duplicates()
print("Duplicados actualizados del df ventas:",ventas_2.duplicated(keep=False).sum())

#Limpieza texto en columnas tipo string
def normalizar_texto(df):
  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip().str.replace(r"[\u200b\t\r\n]", "", regex=True).str.replace(" +", " ", regex=True).str.title()
    return df

#Aplicar funcion de limpieza
ventas_2 = normalizar_texto(ventas_2)
clientes_2 = normalizar_texto(clientes_2)
marketing_2 = normalizar_texto(marketing_2)

#Normalizar fechas con funcion detectando palabra "Fecha"
def normalizar_fecha(df):
  for col in df.select_dtypes(include="object").columns:
    if "fecha" in col.lower():
      df[col] = pd.to_datetime(df[col], errors="coerce", dayfirst=True)
  return df

#Aplicar funcion normalizar fecha en los dataset
ventas_2 = normalizar_fecha(ventas_2)
clientes_2 = normalizar_fecha(clientes_2)
marketing_2 = normalizar_fecha(marketing_2)

#Normalización de valores numericos
def normalizar_numericos(df):
  for col in df.select_dtypes(include="number").columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

#Explorar variable precio
print(ventas_2["precio"].unique())
#Limpiar variable precio eliminar $, eliminar (,) y eliminar espacios
ventas_2["precio"] = ventas_2["precio"].str.replace("$", "", regex=False).str.replace(",", "", regex=False).str.strip()
#Revision variable precio
print(ventas_2["precio"].dtypes)
#Cambiar tipo de datos de la variable precio de objeto a numerico
ventas_2["precio"] = pd.to_numeric(ventas_2["precio"], errors="coerce")

#Explorar variable cantidad
print(ventas_2["cantidad"].unique())
#Cambiar tipo a astype int64 para aceptar nulos
ventas_2["cantidad"] = ventas_2["cantidad"].astype("Int64")

"""Transformación de datos"""

#Crear y calcular la variable ingreso
ventas_2["ingreso"] = ventas_2["precio"] * ventas_2["cantidad"]

#Ingreso total
print("El ingreso total de las ventas fue de:", round(ventas_2["ingreso"].sum(),2))
print("El ingreso promedio de las ventas fue de:", round(ventas_2["ingreso"].mean(),2))
print("La cantidad total de unidades vendidas fue: ", ventas_2["cantidad"].sum())
print("La cantidad promedio de unidades vendidas fue: ", round(ventas_2["cantidad"].mean(),2))
print("El precio promedio de las ventas fue de: ", round(ventas_2["precio"].mean(),2))
print("El producto mas vendido fue: ", ventas_2["producto"].mode()[0])
print("El producto menos vendido fue: ", ventas_2["producto"].value_counts().idxmin())

#Ventas totales por producto
ventas_producto = ventas_2.groupby("producto")["cantidad"].sum().sort_values(ascending=False)
print(ventas_producto.head(5))
#Ingresos totales por producto
ingresos_producto = ventas_2.groupby("producto")["ingreso"].sum().sort_values(ascending=False)
print(ingresos_producto.head(5))

#Crear dataframe por metricas por producto
df_producto = ventas_2.groupby("producto").agg(ingreso_total=("ingreso", "sum"),
                                               cantidad_total=("cantidad", "sum"),
                                               precio_promedio=("precio", "mean"),
                                               registro=("ingreso", "size")).reset_index()

display(df_producto)

#Calcular percentil 80 de ingreso_total
percentil_80 = df_producto["ingreso_total"].quantile(q=0.8, interpolation="linear")
print("El percentil 80 de ingreso total es de:", round(percentil_80))

#Productos de alto rendimiento
df_producto_alto_rendimiento = df_producto[df_producto["ingreso_total"] > percentil_80].sort_values(by="ingreso_total", ascending=False)
display(df_producto_alto_rendimiento)

"""Integracion de datos: Ventas y Marketing"""